version: '3.9'
services:
  database:
    image: 'mysql:5.7.22'
    command: --init-file /data/application/init.sql
    restart: 'always'
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ALLOW_EMPTY_PASSWORD=ok
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:33066"
    volumes:
      - ./init.dev.sql:/data/application/init.sql
      - .dbdata:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    depends_on:
      - database