import "../styles/globals.css";
// import Navbar from '../components/Navbar';
// import {Register} from "../features/utils";
import { Container } from "rsuite";
import Head from "next/head";
import Image from "next/image";
// import Register from './features/register/Register';
import { Provider, useSelector } from "react-redux";
import { Box, ChakraProvider } from '@chakra-ui/react';
import { selectUser } from "../redux/slices/userSlice";
import Navbar from "../components/Navbar";
import { store } from "../redux/store";
import theme from './theme';

function MyApp({ Component, pageProps}) {
  return (
        <ChakraProvider theme={theme}>
          <Head>
            <title>CryptoVapes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <Box w="100%" padding="10vw">
            <Component {...pageProps} />
          </Box>
        </ChakraProvider>
  ); 
}

export default MyApp;
